resume_index:
  path: /resume
  controller: App\Domain\Resume\Controller\Listing

resume_read:
  path: /{id}/read-resume
  controller: App\Domain\Resume\Controller\Read

resume_create:
  path: /publish-resume
  controller: App\Domain\Resume\Controller\Create

resume_update:
  path: /{id}/update-resume
  controller: App\Domain\Resume\Controller\Update
