services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\Domain\Resume\:
    resource: '../../*'
  App\Domain\Resume\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']
